Integrate cookie-policy v3.0.4
canonical-web-and-design/docs.ubuntu.com pull request #269
Opened 2020-10-14 17:26 UTC by anthonydillon

## Done
- Add global-nav and cookie-policy dependencies
- Built with webpack

## QA
- Load the site
- Check the global nav works as expecred
- Check the cookie policy is there and works
- Go to the footer and manage your cookies and see it opens again

## Issue / Card
Fixes https://github.com/canonical-web-and-design/docs.ubuntu.com/issues/268

2020-10-14 17:26 UTC, webteam-app commented
Demo starting at https://docs-ubuntu-com-269.demos.haus

2020-10-15 07:55 UTC, pmahnke commented
@anthonydillon for whatever reason I can't run it locally and the demo can't find the new js, I think the `Dockerfile` needs to also build the javascript as well.

2020-10-15 11:23 UTC, anthonydillon commented
Ah probably, I will take a look

2020-10-15 11:29 UTC, anthonydillon commented
@pmahnke done.

2020-10-15 12:16 UTC, pmahnke commented on webpack.config.entry.js
> +  "global-nav": "./static/js/global-nav.js",
this still doesn't work on the demo... perhaps it should be like

```
  ["global-nav"]: "./static/js/global-nav.js",
  ["cookie-policy"]: "./static/js/cookie-policy.js",
```

2020-10-15 12:16 UTC, pmahnke requested changes
still not running on demos.haus

2020-10-15 15:37 UTC, anthonydillon commented
@pmahnke sorry forgot to actually copy the JS to the dockerfile after building it.

2020-10-15 16:00 UTC, pmahnke commented
@anthonydillon the build is failing - `rpc error: code = Unknown desc = executor failed running [/bin/sh -c yarn run build-js]: exit code: 1` I think the it should be static/js/dist ?

2020-10-15 16:30 UTC, pmahnke approved these changes
works!

2020-10-15 16:30 UTC, merged

2020-10-15 20:45 UTC, anthonydillon commented
Phew, thanks.